### ISSUE TITLE
The function `check` does some internal assertions using the `assert` function it receives as parameter

### ISSUE THREAD

**Issue by gerardo-lima-moonfare** [pinojs/pino-test#13]
The enclosed function `check` uses the same `assert` function it receives as parameter to do some _internal checks_ on `time`, `pid` and `hostname`. It is unnecessary to use default assert function (`deepStrictEqual`) to check on these values and this behaviour also  makes it hard to create assessments on properties -- ie: when `chunkCopy` must contain some property `foo`, we also have to account for the `time`, `pid` and `hostname`.
 
https://github.com/pinojs/pino-test/blob/c22d2aba5a44f7d1cd51aed8f81ff70c1a046f7c/pino-test.js#L38

My suggestion is to to use standard `strictEqual` on the _internal checks_ and only use the `assert` function parameter on the payload (`chunkCopy`), itself. This is a suggestion of implementation:
```js
function check (chunk, expected, assert) {
  const { time, pid, hostname, ...chunkCopy } = chunk

  // internal assertions (*)
  nodeAssert.strictEqual(new Date(time) <= new Date(), true, 'time is greater than Date.now()')
  nodeAssert.strictEqual(pid, process.pid)
  nodeAssert.strictEqual(hostname, os.hostname())

  // "consumer" assertion
  assert(chunkCopy, expected)
}
```

PS: on a side note, I'm not sure whether it's actually useful to run these _internal assertions_ each time a consumer asserts on their logs, but maybe I'm missing something here

**Comment by mcollina** [comment]
Thanks for reporting! Would you like to send a Pull Request to address this issue? Remember to add unit tests.
